name: '职校家园'
 
on:
  schedule:
  # 定时任务
    - cron: '22 13 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    # 首先copy git仓库到虚拟机上
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: '依赖安装'
        run: pip install -r requirements.txt
    # 执行仓库中的脚本文件
      - name: 'Get Weather'
        run: python ./Main.py
